"""Brand-coverage audit for present and *future* upstream files.

The token map in :mod:`hundredways.rules` is validated against the fork's birth
commit and is therefore frozen: a future transform change would grow the
birth-parity drift set.  That leaves two blind spots no map-bound check can see:

* **Discovery** - a brand-new upstream file (or a plain upstream edit) can carry
  a brand *spelling* the map does not know (``HERMESCLOUD``, ``hermescloud``, a
  fresh camel run-on).  No rule fires, so the file ships unbranded and no existing
  gate notices.  :func:`discover_brand_tokens` scans a source tree for
  brand-family occurrences the canonical rules leave untouched and reports them
  as candidate tokens for a human token-map decision.
* **Residue** - a candidate file that still contains a token some rule *would*
  rewrite.  :func:`residual_brand_lines` reports every such line with evidence.

:func:`plan_issues` turns either finding (plus the credential scan) into a
reviewable GitHub-issue draft, and :func:`create_issues` only ever creates them
when explicitly asked.  Creating an issue is a human decision, exactly like
merging a review PR, so the default is a dry run that touches nothing.

This module never edits the token map.  Proposing a spelling is safe; adopting it
is a reviewed change to ``config/rules_override.json`` or a documented reconcile
with a regression test.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import string
import subprocess
from dataclasses import dataclass, field
from pathlib import Path

from .brandassets import AssetIssue, audit_brand_assets
from .brandscan import BrandOccurrence, scan_brand, scan_paths
from .rules import BrandingRules, is_immutable_path, is_locked_path
from .secrets import EXTENDED_SECRET_PATTERNS, redact

# ---------------------------------------------------------------------------
# Discovery: find brand spellings the frozen token map cannot reach.
# ---------------------------------------------------------------------------

# A stem only counts when it is not glued to a preceding *letter of its own
# casing class*, mirroring the rules.  Discovery is case-precise on purpose: the
# camelCase "ou" in ``noUsageData`` is not the lowercase ``nous`` token, and
# ordinary English words ("venous", "synchronous") must never be reported.
_STEM_RE = re.compile(
    r"(?<![a-z])(?P<lower>hermes|nous)"
    r"|(?<![A-Z])(?P<title>Hermes|Nous)"
    r"|(?<![A-Z])(?P<upper>HERMES|NOUS)"
)
_RUN_CHARS = frozenset(string.ascii_letters + string.digits)
_SKIP_DIRS = frozenset({".git", "node_modules"})
_MAX_SCAN_BYTES = 2 * 1024 * 1024

_REVIEW_FOOTER = "Generated by 100Ways \u00b7 review only \u2014 never merge, tag, or release."


def _run_at(text: str, start: int, end: int) -> str:
    """Expand ``[start, end)`` to the surrounding identifier run."""
    while start > 0 and text[start - 1] in _RUN_CHARS:
        start -= 1
    while end < len(text) and text[end] in _RUN_CHARS:
        end += 1
    return text[start:end]


def _iter_text_files(root: str):
    """Yield ``(path, relative)`` for every scannable text file under ``root``."""
    base = Path(root)
    for path in sorted(base.rglob("*")):
        if not path.is_file():
            continue
        if any(part in _SKIP_DIRS for part in path.parts):
            continue
        relative = path.relative_to(base).as_posix()
        if is_immutable_path(relative) or is_locked_path(relative):
            continue
        try:
            if path.stat().st_size > _MAX_SCAN_BYTES:
                continue
        except OSError:
            continue
        yield path, relative


@dataclass(frozen=True)
class BrandTokenCandidate:
    """A brand-family spelling present in the source tree that no rule rewrites."""

    token: str
    count: int
    samples: tuple[str, ...] = ()

    def to_dict(self) -> dict[str, object]:
        return {"token": self.token, "count": self.count, "samples": list(self.samples)}


def discover_brand_tokens(
    root: str,
    rules: BrandingRules | None = None,
    max_samples: int = 8,
) -> list[BrandTokenCandidate]:
    """Return brand spellings in ``root`` that the canonical rules leave untouched.

    Covered spellings (``hermes``, ``NousResearch``, ``HermesCloud``) are dropped;
    only spellings that would ship *unbranded* survive, sorted by frequency.
    """
    rules = rules or BrandingRules()
    counts: dict[str, int] = {}
    samples: dict[str, list[str]] = {}
    for path, relative in _iter_text_files(root):
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        lowered = text.lower()
        if "hermes" not in lowered and "nous" not in lowered:
            continue
        for line_number, line in enumerate(text.splitlines(), start=1):
            for match in _STEM_RE.finditer(line):
                run = _run_at(line, match.start(), match.end())
                if not run or rules.transform_text(run) != run:
                    continue  # covered by an existing rule
                counts[run] = counts.get(run, 0) + 1
                bucket = samples.setdefault(run, [])
                if len(bucket) < max_samples:
                    bucket.append(f"{relative}:{line_number}")
    ordered = sorted(counts.items(), key=lambda item: (-item[1], item[0]))
    return [
        BrandTokenCandidate(token, count, tuple(samples.get(token, ())))
        for token, count in ordered
    ]


# ---------------------------------------------------------------------------
# Residue: a candidate file a rule would still rewrite.
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class BrandResidual:
    """One candidate line that still contains a token an active rule rewrites."""

    path: str
    line: int
    snippet: str
    tokens: tuple[str, ...] = ()

    def to_dict(self) -> dict[str, object]:
        return {
            "path": self.path,
            "line": self.line,
            "snippet": self.snippet,
            "tokens": list(self.tokens),
        }


def _matching_tokens(line: str, rules: BrandingRules) -> tuple[str, ...]:
    return tuple(token.match for token in rules.tokens if token.match in line)


def residual_brand_lines(
    root: str,
    rules: BrandingRules | None = None,
    max_lines: int = 500,
) -> list[BrandResidual]:
    """Return candidate lines that the canonical rules would still rewrite.

    A whole file that is already a transform fixed point costs one comparison
    and is skipped; only a surviving file is scanned line by line for evidence.
    """
    rules = rules or BrandingRules()
    found: list[BrandResidual] = []
    for path, relative in _iter_text_files(root):
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        if rules.transform_text(text) == text:
            continue
        for number, line in enumerate(text.splitlines(), start=1):
            if rules.transform_text(line) == line:
                continue
            found.append(
                BrandResidual(relative, number, line.strip()[:200], _matching_tokens(line, rules))
            )
            if len(found) >= max_lines:
                return found
    return found


# ---------------------------------------------------------------------------
# Credential residency.
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class SecretFinding:
    """One credential-shaped value found in the audited tree."""

    path: str
    line: int
    pattern: str
    snippet: str

    def to_dict(self) -> dict[str, object]:
        return {
            "path": self.path,
            "line": self.line,
            "pattern": self.pattern,
            "snippet": self.snippet,
        }


def scan_credentials(root: str, max_findings: int = 500) -> list[SecretFinding]:
    """Scan ``root`` for credential-shaped values, returning redacted evidence."""
    findings: list[SecretFinding] = []
    for path, relative in _iter_text_files(root):
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        for number, line in enumerate(text.splitlines(), start=1):
            hits = [pattern.pattern for pattern in EXTENDED_SECRET_PATTERNS if pattern.search(line)]
            if not hits:
                continue
            findings.append(
                SecretFinding(relative, number, ", ".join(hits), redact(line.strip())[:200])
            )
            if len(findings) >= max_findings:
                return findings
    return findings


# ---------------------------------------------------------------------------
# The combined audit.
# ---------------------------------------------------------------------------


@dataclass
class BrandAudit:
    """The result of auditing a source tree, and optionally a candidate tree."""

    source_root: str
    candidate_root: str
    scanned_source_files: int = 0
    scanned_candidate_files: int = 0
    uncovered: list[BrandTokenCandidate] = field(default_factory=list)
    residual: list[BrandResidual] = field(default_factory=list)
    secrets: list[SecretFinding] = field(default_factory=list)
    occurrences: list[BrandOccurrence] = field(default_factory=list)
    assets: list[AssetIssue] = field(default_factory=list)

    @property
    def clean(self) -> bool:
        return (
            not self.uncovered
            and not self.residual
            and not self.secrets
            and not self.occurrences
            and not self.assets
        )

    def to_dict(self) -> dict[str, object]:
        return {
            "source_root": self.source_root,
            "candidate_root": self.candidate_root,
            "scanned_source_files": self.scanned_source_files,
            "scanned_candidate_files": self.scanned_candidate_files,
            "clean": self.clean,
            "uncovered": [item.to_dict() for item in self.uncovered],
            "residual": [item.to_dict() for item in self.residual],
            "secrets": [item.to_dict() for item in self.secrets],
            "occurrences": [item.to_dict() for item in self.occurrences],
            "assets": [item.to_dict() for item in self.assets],
        }

    def render_markdown(self) -> str:
        lines = [
            "# 100Ways brand-coverage audit",
            "",
            f"- source: `{self.source_root}` ({self.scanned_source_files} files)",
        ]
        if self.candidate_root:
            lines.append(
                f"- candidate: `{self.candidate_root}` ({self.scanned_candidate_files} files)"
            )
        lines.append(f"- result: **{'CLEAN' if self.clean else 'FINDINGS'}**")
        lines.append("")
        lines += ["## Uncovered brand spellings", ""]
        if self.uncovered:
            lines += ["| spelling | occurrences | sample |", "| --- | ---: | --- |"]
            for candidate in self.uncovered:
                sample = candidate.samples[0] if candidate.samples else ""
                lines.append(
                    f"| `{_cell(candidate.token)}` | {candidate.count} | `{_cell(sample)}` |"
                )
        else:
            lines.append("_none - every brand spelling is covered by a rule._")
        lines += ["", "## Residual candidate lines", ""]
        if not self.candidate_root:
            lines.append("_not checked - no candidate tree given._")
        elif self.residual:
            lines += ["| path | line | snippet |", "| --- | ---: | --- |"]
            for item in self.residual:
                lines.append(f"| `{_cell(item.path)}` | {item.line} | `{_cell(item.snippet)}` |")
        else:
            lines.append("_none - the candidate is a brand fixed point._")
        lines += ["", "## Credential-shaped values", ""]
        if self.secrets:
            lines += ["| path | line | pattern | snippet |", "| --- | ---: | --- | --- |"]
            for item in self.secrets:
                lines.append(
                    f"| `{_cell(item.path)}` | {item.line} | `{_cell(item.pattern)}` | "
                    f"`{_cell(item.snippet)}` |"
                )
        else:
            lines.append("_none detected._")
        lines += ["", "## Strong brand detector", ""]
        if self.occurrences:
            lines += ["| run | path | line |", "| --- | --- | ---: |"]
            for item in self.occurrences:
                lines.append(f"| `{_cell(item.run)}` | `{_cell(item.path)}` | {item.line} |")
        else:
            lines.append("_none - no unstripped hermes/nous run remains._")
        lines += ["", "## Brand assets", ""]
        if self.assets:
            lines += ["| severity | code | path | role |", "| --- | --- | --- | --- |"]
            for item in self.assets:
                lines.append(
                    f"| {item.severity} | `{_cell(item.code)}` "
                    f"| `{_cell(item.path)}` | {item.role} |"
                )
        else:
            lines.append("_none - no asset registry finding._")
        lines.append("")
        return "\n".join(lines)


def _cell(value: str) -> str:
    return value.replace("|", "\\|")


def run_audit(
    source_root: str,
    candidate_root: str = "",
    rules: BrandingRules | None = None,
    max_samples: int = 8,
    assets_root: str = "",
    max_strong: int = 200,
) -> BrandAudit:
    """Audit ``source_root`` for future brand spellings and ``candidate_root`` for residue.

    When ``candidate_root`` is empty the candidate checks are skipped and only the
    source tree is scanned for future-spelling and credential findings.  The
    strong detector always runs against ``target`` = candidate (if given) else
    source, and the owned-asset registry is audited when it exists.
    """
    rules = rules or BrandingRules()
    audit = BrandAudit(source_root=source_root, candidate_root=candidate_root)
    audit.scanned_source_files = sum(1 for _ in _iter_text_files(source_root))
    audit.uncovered = discover_brand_tokens(source_root, rules, max_samples=max_samples)
    target = candidate_root or source_root
    audit.scanned_candidate_files = sum(1 for _ in _iter_text_files(target))
    if candidate_root:
        audit.residual = residual_brand_lines(candidate_root, rules)
    strong = scan_brand(target, max_findings=max_strong)
    audit.occurrences = strong.violations + [o for o in scan_paths(target) if not o.allowed]
    audit.secrets = scan_credentials(target)
    registry = assets_root or os.path.join(target, "config", "owned-assets")
    if os.path.isfile(os.path.join(registry, "manifest.json")):
        audit.assets = audit_brand_assets(registry, candidate_root=candidate_root)
    return audit


# ---------------------------------------------------------------------------
# GitHub-issue drafts (dry run by default).
# ---------------------------------------------------------------------------

_MAP_NOTE = (
    "The canonical token map in `hundredways/rules.py` is frozen by the "
    "birth-parity drift monitor, so 100Ways never edits it automatically.  Adopt "
    "a spelling through the reviewed `config/rules_override.json` token list, or "
    "through a documented, path-scoped reconcile with a regression test."
)


@dataclass(frozen=True)
class IssueDraft:
    """A reviewable GitHub-issue draft.  No side effects until created."""

    key: str
    title: str
    body: str
    labels: tuple[str, ...] = ()
    severity: str = "warning"

    def to_dict(self) -> dict[str, object]:
        return {
            "key": self.key,
            "title": self.title,
            "body": self.body,
            "labels": list(self.labels),
            "severity": self.severity,
        }


def plan_issues(audit: BrandAudit, repo: str = "") -> list[IssueDraft]:
    """Turn an audit into reviewable GitHub-issue drafts.  ``repo`` is advisory.

    The repository name is only carried into :func:`create_issues`; the drafts
    themselves are pure data so they can be reviewed or archived first.
    """
    drafts: list[IssueDraft] = []
    if audit.uncovered:
        rows = ["| spelling | occurrences | sample |", "| --- | ---: | --- |"]
        for candidate in audit.uncovered:
            sample = candidate.samples[0] if candidate.samples else ""
            rows.append(f"| `{_cell(candidate.token)}` | {candidate.count} | `{_cell(sample)}` |")
        body = "\n".join(
            [
                "The canonical token map left these brand-family spellings untouched while "
                "scanning the source tree.  A future upstream file carrying one of them would "
                "ship unbranded, because no rule fires on it.",
                "",
                *rows,
                "",
                _MAP_NOTE,
                "",
                _REVIEW_FOOTER,
            ]
        )
        drafts.append(
            IssueDraft(
                key="uncovered-brand-tokens",
                title=(
                    "Brand audit: "
                    f"{len(audit.uncovered)} uncovered brand spelling(s) need a token-map decision"
                ),
                body=body,
                labels=("brand-audit", "needs-review"),
            )
        )
    if audit.residual:
        rows = ["| path | line | snippet |", "| --- | ---: | --- |"]
        for item in audit.residual:
            rows.append(f"| `{_cell(item.path)}` | {item.line} | `{_cell(item.snippet)}` |")
        body = "\n".join(
            [
                f"The candidate still contains {len(audit.residual)} line(s) that an active brand "
                "rule would rewrite, so it is not a brand fixed point.",
                "",
                *rows,
                "",
                _REVIEW_FOOTER,
            ]
        )
        drafts.append(
            IssueDraft(
                key="residual-brand-lines",
                title=f"Brand audit: {len(audit.residual)} candidate line(s) are not fully branded",
                body=body,
                labels=("brand-audit", "needs-review"),
                severity="blocking",
            )
        )
    if audit.secrets:
        rows = ["| path | line | pattern | snippet |", "| --- | ---: | --- | --- |"]
        for item in audit.secrets:
            rows.append(
                f"| `{_cell(item.path)}` | {item.line} | `{_cell(item.pattern)}` | "
                f"`{_cell(item.snippet)}` |"
            )
        body = "\n".join(
            [
                f"Found {len(audit.secrets)} credential-shaped value(s).  The snippet column is "
                "redacted; rotate any real key before acting on this issue.",
                "",
                *rows,
                "",
                _REVIEW_FOOTER,
            ]
        )
        drafts.append(
            IssueDraft(
                key="credential-residency",
                title=f"Security audit: {len(audit.secrets)} credential-shaped value(s) detected",
                body=body,
                labels=("security", "needs-review"),
                severity="blocking",
            )
        )
    if audit.occurrences:
        rows = ["| run | path | line |", "| --- | --- | ---: |"]
        for item in audit.occurrences:
            rows.append(f"| `{_cell(item.run)}` | `{_cell(item.path)}` | {item.line} |")
        body = "\n".join(
            [
                f"The strong detector found {len(audit.occurrences)} upstream hermes/nous run(s) "
                "that the frozen map leaves untouched. A human token-map decision is required.",
                "",
                *rows,
                "",
                _REVIEW_FOOTER,
            ]
        )
        drafts.append(
            IssueDraft(
                key="strong-brand-violations",
                title=f"Brand detector: {len(audit.occurrences)} unstripped hermes/nous run(s)",
                body=body,
                labels=("brand-audit", "needs-review"),
                severity="blocking",
            )
        )
    if audit.assets:
        rows = ["| severity | code | path | role |", "| --- | --- | --- | --- |"]
        for item in audit.assets:
            rows.append(
                f"| {item.severity} | `{_cell(item.code)}` | `{_cell(item.path)}` | {item.role} |"
            )
        body = "\n".join(
            [
                f"{len(audit.assets)} owned-asset registry finding(s). A logo or icon that is "
                "not referenced is never materialized, so upstream bytes can ship.",
                "",
                *rows,
                "",
                _REVIEW_FOOTER,
            ]
        )
        drafts.append(
            IssueDraft(
                key="brand-asset-registry",
                title=f"Brand assets: {len(audit.assets)} registry finding(s)",
                body=body,
                labels=("brand-audit", "assets", "needs-review"),
                severity="blocking",
            )
        )
    return drafts


def render_issues_markdown(drafts: list[IssueDraft]) -> str:
    """Render issue drafts as a single deterministic markdown artifact."""
    if not drafts:
        return "# 100Ways issue drafts\n\n_no findings to report._\n"
    lines = ["# 100Ways issue drafts", "", f"{len(drafts)} draft(s).", ""]
    for draft in drafts:
        labels = ", ".join(draft.labels) or "-"
        lines += [
            f"## [{draft.severity}] {draft.title}",
            "",
            f"- key: `{draft.key}`",
            f"- labels: {labels}",
            "",
            draft.body,
            "",
        ]
    return "\n".join(lines)


def create_issues(
    repo: str,
    drafts: list[IssueDraft],
    apply: bool = False,
) -> list[dict[str, object]]:
    """Create the drafts as GitHub issues **only** when ``apply`` is true.

    The default is a dry run: it returns the plans and touches nothing.  Creation
    uses the ``gh`` CLI, which must be authenticated.  Because opening issues is a
    human decision, this is never wired into a workflow.
    """
    if not apply:
        return [
            {
                "key": draft.key,
                "title": draft.title,
                "labels": list(draft.labels),
                "action": "skipped",
            }
            for draft in drafts
        ]
    if shutil.which("gh") is None:
        return [
            {"key": draft.key, "title": draft.title, "error": "gh CLI not on PATH"}
            for draft in drafts
        ]
    results: list[dict[str, object]] = []
    for draft in drafts:
        command = [
            "gh", "issue", "create", "--repo", repo,
            "--title", draft.title, "--body", draft.body,
        ]
        for label in draft.labels:
            command += ["--label", label]
        proc = subprocess.run(command, capture_output=True, text=True)
        if proc.returncode == 0:
            results.append({"key": draft.key, "title": draft.title, "url": proc.stdout.strip()})
            continue
        # A missing label makes gh fail; retry once without labels and record that.
        retry = [
            "gh", "issue", "create", "--repo", repo,
            "--title", draft.title, "--body", draft.body,
        ]
        retry_proc = subprocess.run(retry, capture_output=True, text=True)
        if retry_proc.returncode == 0:
            results.append(
                {
                    "key": draft.key,
                    "title": draft.title,
                    "url": retry_proc.stdout.strip(),
                    "labels": "skipped: label not found",
                }
            )
        else:
            results.append(
                {"key": draft.key, "title": draft.title, "error": retry_proc.stderr.strip()}
            )
    return results


def write_json(audit: BrandAudit, path: str) -> None:
    """Write the audit result as deterministic JSON."""
    Path(path).write_text(json.dumps(audit.to_dict(), indent=2) + "\n", encoding="utf-8")
