"""Git operations: verified push, PR, and packaging.

The verified pipeline lives in git: the rules gate proves a tree is faithful,
``pack`` archives the verified branded result as a zip (the "ready Nastech
version"), ``push_branch`` + ``open_pr`` land it on a branch and raise a PR
against the Nastech repo.  In CI these run from GitHub Actions; locally they
use the ``gh`` CLI when available.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
from pathlib import Path


def _run(cmd: list[str]) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, capture_output=True, text=True)


def _run_ok(cmd: list[str], what: str) -> str:
    proc = _run(cmd)
    if proc.returncode != 0:
        raise RuntimeError(f"{what} failed: {proc.stderr.strip() or proc.stdout.strip()}")
    return proc.stdout.strip()


def has_gh() -> bool:
    return shutil.which("gh") is not None


def ensure_branch(repo: str, branch: str) -> None:
    """Create ``branch`` at HEAD if it does not exist yet."""
    if branch not in _run_ok(["git", "-C", repo, "branch", "--format=%(refname:short)"], "list branches").splitlines():
        _run_ok(["git", "-C", repo, "branch", branch], f"create branch {branch}")


def pack_zip(repo: str, out_path: str) -> str:
    """Archive the current HEAD tree (minus .git) as a zip.

    ``git archive`` is byte-identical to the committed tree, so the zip IS the
    verified branded update, ready to deploy or attach to a release.
    """
    out_path = os.path.abspath(out_path)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "wb") as fh:
        proc = subprocess.run(["git", "-C", repo, "archive", "--format=zip", "-o", "-", "HEAD"], capture_output=True)
        if proc.returncode != 0:
            raise RuntimeError(f"git archive failed: {proc.stderr.strip()}")
        fh.write(proc.stdout)
    return out_path


def push_branch(repo: str, branch: str, remote: str = "origin") -> str:
    """Push ``branch`` to ``remote`` and return the remote head sha."""
    _run_ok(["git", "-C", repo, "push", "-u", remote, branch], f"push {branch}")
    return _run_ok(["git", "-C", repo, "rev-parse", f"{remote}/{branch}"], "remote head")


def open_pr(
    branch: str,
    target_repo: str,
    title: str,
    body: str,
    target_branch: str = "main",
    base_url: str = "https://github.com",
) -> str:
    """Open a PR from ``branch`` (on the local origin) into ``target_repo``.

    Uses ``gh`` when available.  ``GH_TOKEN`` must have push access to both
    the fork (to host the branch) and the target repo.
    """
    if not has_gh():
        raise RuntimeError("gh CLI not installed; cannot open a PR")
    proc = _run([
        "gh", "pr", "create",
        "--repo", target_repo,
        "--base", target_branch,
        "--head", branch,
        "--title", title,
        "--body", body,
    ])
    if proc.returncode != 0:
        raise RuntimeError(f"gh pr create failed: {proc.stderr.strip() or proc.stdout.strip()}")
    return proc.stdout.strip()


def pr_body(report_lines: list[str]) -> str:
    """Standardized PR body summarizing the verified update."""
    return "\n".join([
        "## 100Ways verified update",
        "",
        "The branding rules gate passed; this update is byte-faithful to "
        "upstream after branding.",
        "",
        "### report",
        *[f"- {line}" for line in report_lines],
        "",
        "Auto-generated by 100Ways.",
    ])


def push_signal(repo: str, payload: dict, url: str = "https://github.com") -> str:
    """POST a repository_dispatch signal so a 100Ways worker can react."""
    import urllib.request

    token = os.getenv("GH_TOKEN", "")
    if not token:
        raise RuntimeError("GH_TOKEN required for repository_dispatch")
    req = urllib.request.Request(
        f"{url}/{payload['repo']}/dispatches",
        data=json.dumps({"event_type": payload.get("event_type", "100ways-update"), "client_payload": payload}).encode(),
        headers={"Authorization": f"Bearer {token}", "Accept": "application/vnd.github+json", "User-Agent": "100ways"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        return f"dispatch {resp.status}"
