"""README generation: a machine-maintained project README.

The README is regenerated by CI (``stage-readme.yml``) from the ways
registry, the achievement catalog, and the owned-assets registry - so the
counts ("200 ways", "N trophies") never drift from the code that owns them.
Deterministic: given the same inputs it emits the same bytes.
"""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass

from .achievements import ACHIEVEMENTS, Achievements
from .ways import WAYS


@dataclass(frozen=True)
class ReadmeInputs:
    ways: list = None          # Way list
    achievements: dict = None  # name -> Achievement
    state_dir: str = ""        # where achievements.json lives (empty = none unlocked)
    owned_count: int = 0       # owned-assets registry entry count


def _plural(n: int, singular: str, plural: str | None = None) -> str:
    return singular if n == 1 else (plural or singular + "s")


def render_readme(inp: ReadmeInputs) -> str:
    ways = inp.ways if inp.ways is not None else WAYS
    achievements = inp.achievements if inp.achievements is not None else ACHIEVEMENTS
    by_category = Counter(w.category for w in ways)
    ach = Achievements(inp.state_dir) if inp.state_dir else None
    trophies = ach.trophies() if ach else []
    lines = [
        "# 100Ways",
        "",
        "A rebrand-safe fork-sync engine that ports the upstream Hermes agent",
        "into the Nastech fork while keeping parity and the brand intact.",
        "",
        "## At a glance",
        "",
        f"- {len(ways)} ways across {len(by_category)} strategy categories",
        f"- {len(achievements)} achievements, {len(trophies)} unlocked",
        f"- {inp.owned_count} owned-asset registry entries (see config/owned-assets/)",
        f"- {len(_ordered_stages())} pipeline stages per update run",
        "",
        "## Ways",
        "",
    ]
    for category in sorted(by_category):
        names = [w.name for w in ways if w.category == category]
        lines.append(f"### {category} ({len(names)} {_plural(len(names), 'way')})")
        lines.append("")
        for name in names:
            lines.append(f"- {name}")
        lines.append("")
    lines.append("## Achievements")
    lines.append("")
    for name, meta in achievements.items():
        mark = "✅" if any(t.name == meta.name for t in trophies) else "▢"
        lines.append(f"- {mark} {meta.emoji} {name} — {meta.description}")
    lines.append("")
    lines.append("## Trophies")
    lines.append("")
    if trophies:
        for t in trophies:
            lines.append(f"- {t.emoji} {t.name} — {t.description}")
    else:
        lines.append("_None unlocked yet._")
    lines.append("")
    lines.append("## Pipeline stages")
    lines.append("")
    for i, stage in enumerate(_ordered_stages(), 1):
        lines.append(f"{i}. {stage}")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("Generated by `100ways readme`; do not edit by hand.")
    lines.append("")
    return "\n".join(lines)


def _ordered_stages():
    # imported lazily so `readme` never drags the git plumbing in
    from .updates import STAGES
    return STAGES


def render_readme_for_repo(repo: str, state_dir: str = "", owned_count: int = 0) -> str:
    """Convenience: build ReadmeInputs from a repo checkout and render."""
    return render_readme(ReadmeInputs(state_dir=state_dir, owned_count=owned_count))
